version: "3.3"
services: 
  exporter:
    container_name: 'exporter'
    image: 'exporter'
    build:
      context: .
      dockerfile: 'apps/exporter/Dockerfile'
    volumes: 
      - /var/log/kubernetes/apiserver/:/var/log/kubernetes/apiserver/:rw
  analyzer:
    container_name: 'analyzer'
    image: 'analyzer'
    env_file: .env
    build:
      context: .
      dockerfile: 'apps/analyzer/Dockerfile'
    ports: 
      - 8000:8000
  database:
    container_name: "postgres-db"
    image: "postgres"
    env_file: .env
    ports: 
      - 5432:5432
    volumes: 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  
