version: "3.3"
services: 
  exporter:
    image: 'exporter'
    build:
      context: .
      dockerfile: 'apps/exporter/Dockerfile'
    container_name: 'exporter'
  analyzer:
    image: 'analyzer'
    build:
      context: .
      dockerfile: 'apps/analyzer/Dockerfile'
    container_name: 'analyzer'
  database:
    image: "postgres"
    container_name: "postgres-db"
    env_file: .env
    ports: 
      - 5432:5432
    volumes: 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  # reddit-flow:
  #   image: 'reddit-flow'
  #   build: 
  #     context: .
  #     dockerfile: reddit_flow_bot/Dockerfile
  #   container_name: 'reddit-flow'
  #   volumes: 
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   env_file: .env
  # sender:
  #   image: 'sender'
  #   build: 
  #     context: .
  #     dockerfile: sender/Dockerfile
  #   container_name: 'sender'
  #   volumes: 
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   env_file: .env
  # postgres:
  #   image: postgres:13
  #   container_name: "tgPhotoBot-postgres"
  #   restart: on-failure
  #   env_file: .env
  #   ports: 
  #     - 5432:5432
  #   volumes: 
  #     - ~/.volumes/postgres:/var/lib/postgresql/data
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro


  
