apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - name: 'postgres-port'
      port: 5432
      targetPort: 5432
  externalIPs:
    - '45.85.117.217'
  selector:
   app: postgres
