apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"

---

apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "v1.24.1"

networking:
  podSubnet: "10.244.0.0/16"

apiServer:
  timeoutForControlPlane: 10m0s
  extraArgs:
    audit-log-path: "/var/log/kubernetes/apiserver/audit.log"
    audit-policy-file: "/etc/kubernetes/audit-policies/policy.yaml"
  extraVolumes:
  - name: "audit-policy"
    hostPath: "/etc/kubernetes/audit-policies/"
    mountPath: "/etc/kubernetes/audit-policies/"
    readOnly: false
  - name: "audit-log"
    hostPath: "/var/log/kubernetes/apiserver/"
    mountPath: "/var/log/kubernetes/apiserver/"
    readOnly: false
