"""init revision

Revision ID: 2bf80f71f751
Revises: 
Create Date: 2022-12-25 18:07:00.293125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf80f71f751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_data',
    sa.Column('analyzed_data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_raw', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('analyzed_data_id')
    )
    op.create_table('analyzed_metadata',
    sa.Column('analyzed_metadata_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_data_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_data_id'], ['analyzed_data.analyzed_data_id'], ),
    sa.PrimaryKeyConstraint('analyzed_metadata_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyzed_metadata')
    op.drop_table('analyzed_data')
    # ### end Alembic commands ###
