"""date added

Revision ID: 9de8ebae5acd
Revises: a02cb8bf3654
Create Date: 2022-12-25 00:46:14.624025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de8ebae5acd'
down_revision = 'a02cb8bf3654'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyzed_metadata', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyzed_metadata', 'date_created')
    # ### end Alembic commands ###
