"""orm updated

Revision ID: a02cb8bf3654
Revises: f81879a435bd
Create Date: 2022-12-25 00:13:00.269220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02cb8bf3654'
down_revision = 'f81879a435bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_data',
    sa.Column('analyzed_data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('object_raw', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('analyzed_data_id')
    )
    op.create_table('analyzed_metadata',
    sa.Column('analyzed_metadata_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analyzed_data_id', sa.INTEGER(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_data_id'], ['analyzed_data.analyzed_data_id'], ),
    sa.PrimaryKeyConstraint('analyzed_metadata_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyzed_metadata')
    op.drop_table('analyzed_data')
    # ### end Alembic commands ###
