apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
# kubernetesVersion: v1.16.0
apiServer:
  extraArgs:
    # anonymous-auth: "false"
    # enable-admission-plugins: AlwaysPullImages,DefaultStorageClass
    audit-log-path: "/var/log/kubernetes/apiserver/audit.log"
    audit-policy-file: "/etc/kubernetes/audit-policies/policy.yaml"
    criSocket: "unix:///var/run/containerd/containerd.sock"
    podNetworkCidr: "10.244.0.0/16"
