apiVersion: v1
kind: ConfigMap
metadata:
  name: "analyzer-configmap"
  labels:
    app: "analyzer"
data:
  # POSTGRES_USER: ""
  # POSTGRES_PASS: ""
  POSTGRES_HOST: "10.42.0.21"
  POSTGRES_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "analyzer"
  template:
    metadata:
      labels:
        app: "analyzer"
    spec:
      containers:
        - name: 'analyzer'
          image: 'kubewatcher/analyzer:0.2'
          imagePullPolicy: "Never"
          resources: 
           limits:
            memory: "128Mi"
            cpu: "200m"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: "analyzer-configmap"
          volumeMounts:
            - name: "seclector-config"
              # TODO
          env:
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "postgres-main-user-creds"
                  key: "username"
                  optional: false
            - name: "POSTGRES_PASS"
              valueFrom:
                secretKeyRef:
                  name: "postgres-main-user-creds"
                  key: "password"
                  optional: false
      nodeSelector:
        apply_analyzer: "true"
---
apiVersion: v1
kind: Service
metadata: 
  name: analyzer
  labels:
    app: "analyzer"
spec:
  type: LoadBalancer
  ports:
    - name: "analyzer-port"
      port: 8000
      targetPort: 8000
  # externalIPs: 
  #   - "192.168.0.106"
  selector:
    app: "analyzer"